### PR TITLE
fix: make types available to users

### LINKED ISSUE #4: types should not be internal
image

Just like the above, types should not be internal, otherwise users can't customize their ProfileTypes.

### PR DESCRIPTION
**Pull request by kolesnikovae**
Closes #4

### CODE REVIEW

**Comment by kavu** [comment]
@kolesnikovae Hi Anton! You are moving the package `types` from internal, which is good, but example states that we are using type from the root `pyroscope` package:

```go
		ProfileTypes: []pyroscope.ProfileType{
			pyroscope.ProfileCPU,
			pyroscope.ProfileAllocObjects,
			pyroscope.ProfileAllocSpace,
			pyroscope.ProfileInuseObjects,
			pyroscope.ProfileInuseSpace,
		},
```

That will create additional confusion for the users. Maybe you wanna move `types.go` to `pyroscope` package? WDYT?

**Comment by kolesnikovae** [comment]
Right, I think it's better to fix it in the way that `ProfileType` could be imported from `pyroscope`.

But it's not that simple: `ProfileType` is also imported from `session` package which, in turn, is imported in `pyroscope`. Moving `ProfileType` type to `pyroscope` package would create a recursive dependency. We could either move `session` to `pyroscope`, or create aliases. I decided to go the first way.

**Comment by kolesnikovae** [comment]
@kavu Thank you for pointing this out!

I'm wondering if we should remove `ProfileType` configuration from examples (not from the documentation!), just to make them more concise. And I do believe we need to add API tests.

**Comment by koolay** [comment]
@kolesnikovae Hi, we need it too.  The golang client dose't  work now.

**Comment by kavu** [comment]
@koolay you can easily make it work with minimal config, without specifying the profile types:

```go
	pyroscope.Start(pyroscope.Config{
		ApplicationName: "test-crash",
		ServerAddress:   "http://localhost:4040",
		Logger:          logger,
	})
```

This will work perfectly, as in this case, Pyroscope will use a default list of profilers that looks like:

```
var DefaultProfileTypes = []ProfileType{
	ProfileCPU,
	ProfileAllocObjects,
	ProfileAllocSpace,
	ProfileInuseObjects,
	ProfileInuseSpace,
}
```

**Pull request merged**
